### ISSUE TITLE
[Question] In which regions is this layer available?

### ISSUE THREAD

**Issue by Giaco9** [alexandredavi/openssl-lambda-layer#1]
Hi,
 thank you for your amazing job! This layer is really useful for me!
May I ask you in which regions is this layer available? All AWS regions where layers are supported? What happens when AWS open a new region?

Thank you again

**Comment by alexandredavi** [comment]
HI,
This Lambda layer is availiable in all AWS regions. When AWS open a new region we have to re-run the build and publish script files. The publish script deploy the layer to all availiable AWS regions.

You can also run this files to create this layer on your own AWS account, just configure the AWS cli with your credendentials and run the src/build.sh and the src/publish.sh. You need to have Docker to do this.

**Comment by Giaco9** [comment]
Thank you!
