### ISSUE TITLE
Doesn't work on Node.js v18 and v20 runtinmes

### ISSUE THREAD

**Issue by bitconym** [alexandredavi/openssl-lambda-layer#6]
The Node.js v16 will soon be deprecated on AWS Lambda, so would be good to get the OpenSLL Layer working on the newer runtimes v18 and v20.

**Comment by roharvey** [comment]
I made [a gist](https://gist.github.com/roharvey/08026cb83f1366537df751729972d712) of this which seems to work with the [latest runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-supported) (those which use Amazon Linux 2023). I feel a bit more comfortable building it myself anyway. You just need docker to build it and then create a lambda layer with the layer/layer.zip file.

**Comment by bitconym** [comment]
Thank you @roharvey for the gist, I didn't know it was that simple to build it myself!
